### ISSUE TITLE
cannot import keyring.py27compat.unicode_str

### ISSUE THREAD

**Issue by Danamir** [jaraco/keyrings.alt#17]
Apparently they renamed `keyring.py27compat.unicode_str` to `text_type`, cf. [keyring github page](https://github.com/jaraco/keyring/commit/af31b7e9b8bd13a622ddd395f8023fd1b2db59a3).

I had a script using keyrings.alt that stopped working two days ago, after changing `unicode_str` to `text_type` in keyrings.alt.Gnome it works again.

**Comment by jaraco** [comment]
doh. Sorry about that.

**Comment by jaraco** [comment]
2.2, being released now, uses six to bypass the issue and decouple that aspect of the dependency (so it should work with old and new versions of keyring).
