### ISSUE TITLE
File backend uses pycrypto but it's not listed in install requires

### ISSUE THREAD

**Issue by aikchar** [jaraco/keyrings.alt#18]
In [file.py](https://github.com/jaraco/keyrings.alt/blob/master/keyrings/alt/file.py#L50):

    from Crypto.Protocol.KDF import PBKDF2

In [setup.py](https://github.com/jaraco/keyrings.alt/blob/master/setup.py#L27):

    install_requires=[
        'six',
    ],

[secretstorage](https://github.com/mitya57/secretstorage/), used by [keyring](https://github.com/jaraco/keyring/blob/master/setup.py#L34), has [moved from pycrypto to cryptography](https://github.com/mitya57/secretstorage/commit/9e871be28813a676d9117507e2468d04c3d860a0#diff-2eeaed663bd0d25b7e608891384b7298).

Better to move to cryptography from pycrypto to standardize on a single dependency. If that's hard to do in the short term, maybe add pycrypto as a requirement in setup.py.

Disclaimer: newbie to this project so I'm not aware of the background reasons for current situation.

**Comment by jaraco** [comment]
All in favor. These alternate backends are generally deprecated, so if you can rely on those in keyring, that's preferable. I'd welcome patches to use cryptography instead.

**Comment by frispete** [comment]
Hmm, sure, cryptography in better supported compared to pycrypto. But has its own share of problems, e.g. its dependency on openssl, which results in availability of certain algorithms for certain openssl versions only and updating openssl from 1.0.2 to 1.1.0 on a linux system is a perfect recipe for disaster for that matter...

OTOH, pycrypto is fully self contained. With [PyCryptodome](https://github.com/Legrandin/pycryptodome), there's a decent well formed and supported successor of this unmaintained package.

@aikchar If you're looking for an encrypted file backend, you may want to check out [keyrings.cryptfile](https://github.com/frispete/keyrings.cryptfile), which is a cryptographically advanced alternative to the encryped file backends of this project. For the reasons given above, it is using PyCryptodome for encryption (all available authenticated symmetric AES modes) and argon2_cffi as KDF.

**Comment by aikchar** [comment]
> These alternate backends are generally deprecated

I need keyrings.alt (or something like it) because some lightly sensitive information is shipped with the code. It's a lot easier to ship an encrypted file that works out of the box than to ask people to spend a lot more time in setup.

> you may want to check out keyrings.cryptfile, which is a cryptographically advanced alternative to the encryped file backends of this project

Thanks. I'll take a look at keyrings.cryptfile as well.

**Comment by jaraco** [comment]
By the way, PyCrypto is an optional dependency, and the keyrings are disabled when the necessary libraries aren't available, by design. I don't want to add it as a dependency as there may be users of other backends who do not rely on the dependency.
