### ISSUE TITLE
Support pyfs 2

### ISSUE THREAD

**Issue by sebix** [jaraco/keyrings.alt#20]
There are some incompatibilities with the [Python's filesystem abstraction layer (fs)](https://pypi.python.org/pypi/fs/2.0.4).

* `ResourceNotFoundError` has been replaced by `ResourceNotFound`, see #19
* `fs.opener.fsopendir` does no longer exist (e.g. `fs.opener.fsopendir(self.filename).open('kr.cfg', mode)`)
* `fs.opener.opener` does not exist (e.g. `s.opener.opener.parse(self.filename, writeable=writeable)`

**Comment by jaraco** [comment]
The code as written still works, although it's pinned to `pyfs<2`. Supporting pyfs 2+ will be a new feature. I welcome contributions.

**Comment by jaraco** [comment]
It sounds as if there's little interest in this effort. I'm going to close this ticket as it's stale, but I welcome anyone to revive the effort in the future.
