### ISSUE TITLE
file keyring: what ensures the password is a string?

### ISSUE THREAD

**Issue by nacc** [jaraco/keyrings.alt#23]
In my application, I'm getting a backtrace because the passed-in password to set_password is already base64-encoded. I'm trying to figure out if that's a bug in the caller or the callee (in that it should only encode the string if it's not a bytes object).

https://github.com/jaraco/keyrings.alt/blob/2702f9159502fc784815c50e03002991b6745f19/keyrings/alt/file_base.py#L131

**Comment by mitya57** [comment]
Please see jaraco/keyring#275. The password should be a unicode string, not bytes.

I also don’t see why you would want to base64 encode the password before passing it to Keyring. It should accept any unicode string. If there is some unicode string that produces an error, please paste it, as that is probably a bug in some backend.

**Comment by mitya57** [comment]
I have now created MR #23 which should make the error message more clear (`TypeError` rather than `AttributeError`). This change should only affect Python 3, in Python 2 both unicode strings and ASCII bytestrings continue working.
