### ISSUE TITLE
EncryptedKeyring.keyring_key behaves strange under certain conditions

### ISSUE THREAD

**Issue by frispete** [jaraco/keyrings.alt#42]
Hi Jaraco,

I'm facing a strange [issue](https://github.com/frispete/keyrings.cryptfile/issues/15) in [keyrings.cryptfile](https://github.com/frispete/keyrings.cryptfile) that boils down to:

After adapting `keyrings.cryptfile` to the new `keyring` test suite by fetching `file.py`, `file_base.py` and relevant `tests` from this project, an incompatibility appeared in behavior: before, it was possible to execute this sequence:

```
from keyrings.cryptfile.cryptfile import CryptFileKeyring
kr = CryptFileKeyring()
kr.keyring_key = "test"
kr.set_password("foo", "bar", "test_password")
```

and retrieve it again with:
```
from keyrings.cryptfile.cryptfile import CryptFileKeyring
kr = CryptFileKeyring()
kr.keyring_key = "test"

print(kr.get_password("foo", "bar"))
```

Now, the side effect in [EncryptedKeyring.keyring_key()](https://github.com/jaraco/keyrings.alt/blob/74c38a061b0463f295ceb6b1a658e8e3c56ca669/keyrings/alt/file.py#L87) of initializing the keyring file isn't performed properly anymore, resulting in a damaged `keyring file`. It is missing the `[keyring_2Dsetting]` section. I've attempted to fix the issue [here](https://github.com/frispete/keyrings.cryptfile/commit/5a846c583ae756663fcad4ed382b258a00e809bc), but now, `TestEncryptedFileKeyring::test_wrong_password` fails, and I'm not sure, if this is a good enough approach, since this should land in your project one day as well...

What do you think?

**Comment by jaraco** [comment]
I looked at this briefly but ran out of energy before I had any insight. It seems at first blush like there's an issue with keyrings.cryptfile that emerged due to some changes in that project. If so, I'd recommend bisecting that project to identify the pertinent change. I can dig in more at some point, but I'm not sure when.

**Comment by jaraco** [comment]
I'd start by writing a test that attempts to assert the desired behavior but instead exhibits the undesired behavior. I understand you want to be able to set the key for a keyring programmatically, but still have the initialization logic happen. Your draft seems reasonable, although I prefer not to have extra instance properties (`keyring_key`) and special values (`None`) where possible. Stlil, if you can write a test that captures what you wish to happen, that would be a good start to work out a solution.
