### ISSUE TITLE
pyfs backend seems to be incompatible with fs-2.4.16, even though requirements declare <3

### ISSUE THREAD

**Issue by mgorny** [jaraco/keyrings.alt#49]
I have fs-2.4.16 installed, and all pyfs tests are skipped. If I remove the "skipif", I get lots of test failures, such as:

```pytb
_______________________________ TestUnencryptedMemoryPyfilesystemKeyringNoSubDir.test_password_set_get ________________________________

self = <keyrings.alt.pyfs.PlaintextKeyring object at 0x7f14bb08f350>, mode = 'r'

    def _open(self, mode='r'):
        """Open the password file in the specified mode"""
        open_file = None
        writeable = 'w' in mode or 'a' in mode or '+' in mode
        try:
>           open_file = self._get_opener(mode, writeable)

keyrings/alt/pyfs.py:86: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <keyrings.alt.pyfs.PlaintextKeyring object at 0x7f14bb08f350>, mode = 'r', writeable = False

    def _get_opener(self, mode, writeable):
        # NOTE: currently the MemOpener does not split off any filename
        #       which causes errors on close()
        #       so we add a dummy name and open it separately
        if self.filename.startswith('mem://') or self.filename.startswith('ram://'):
>           open_file = fs.opener.fsopendir(self.filename).open('kr.cfg', mode)
E           AttributeError: module 'fs.opener' has no attribute 'fsopendir'

keyrings/alt/pyfs.py:146: AttributeError

During handling of the above exception, another exception occurred:

self = <tests.test_pyfs.TestUnencryptedMemoryPyfilesystemKeyringNoSubDir object at 0x7f14b9fd0650>

    def test_password_set_get(self):
        password = random_string(20)
        username = random_string(20)
        service = random_string(20)
>       self.check_set_get(service, username, password)

/usr/lib/python3.11/site-packages/keyring/testing/backend.py:72: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/lib/python3.11/site-packages/keyring/testing/backend.py:58: in check_set_get
    assert keyring.get_password(service, username) is None
keyrings/alt/pyfs.py:177: in get_password
    password_base64 = self.config.get(service, username).encode()
keyrings/alt/pyfs.py:166: in config
    raw_config.read_file(self._open() or [])
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <keyrings.alt.pyfs.PlaintextKeyring object at 0x7f14bb08f350>, mode = 'r'

    def _open(self, mode='r'):
        """Open the password file in the specified mode"""
        open_file = None
        writeable = 'w' in mode or 'a' in mode or '+' in mode
        try:
            open_file = self._get_opener(mode, writeable)
>       except fs.errors.ResourceNotFoundError:
E       AttributeError: module 'fs.errors' has no attribute 'ResourceNotFoundError'

keyrings/alt/pyfs.py:87: AttributeError
```

So I guess the requirement `fs>=0.5,<3` is incorrect since 2.4.x doesn't work. FWICS the tests are also skipped on CI.

**Comment by jhgit** [comment]
I have not done the archeology yet, so I don't know exactly which version of 'fs' is no longer compatible with keyrings.alt, but you're right that the <3 test is not correct right now as fs 2.4.16 will not work with keyrings.alt 4.2.0.

As more packages grow dependency on the latest 'fs' module, this will become more of a problem for keyrings.alt.  For example 'fonttools' has this requirement:

            "fs >= 2.2.0, < 3",

There should probably be some work to support newer 'fs' in keyrings.alt.  I took a quick look - it doesn't seem trivial at a glance.

**Comment by jhgit** [comment]
> I have not done the archeology yet, so I don't know exactly which version of 'fs' is no longer compatible with keyrings.alt, but you're right that the <3 test is not correct right now as fs 2.4.16 will not work with keyrings.alt 4.2.0.

It looks like [fs >= 2](https://github.com/PyFilesystem/pyfilesystem2) has not been compatible with keyrings.alt's pyfs since the inception of the newer 'fs v2' in 2016.  So without an update to the keryings.alt implementation of support for the 'fs' module (in `alt/pyfs.py`), the requirement should probably be changed to `fs>=0.5,<2`.

**Comment by jhgit** [comment]
For more history, see:
 - issue #11
 - issue #20
 - pull request #29
 - pull request #19
 - pull request #44 (committed incorrectly it seems)

**Comment by jaraco** [comment]
> For more history, see:

Thanks for the investigation, especially for the link to #44, which indicates how this dependency was incorrectly bumped.

As noted in #50, there are no viable versions of `fs` that work with this library, and since no one seems to have been bothered by the broken dependency (lack of support in pyfs), I'm inclined to just drop the functionality.
