### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by frispete** [jaraco/keyrings.alt#6]
Dear Jaraco,

would you assign a license to your package, please.

Without a license, your package cannot be distributed properly.

Thanks,
Pete

**Comment by jakirkham** [comment]
Maybe PR ( https://github.com/jaraco/keyrings.alt/pull/8 ) will help.

**Comment by jakirkham** [comment]
cc @astaric

**Comment by jaraco** [comment]
https://github.com/jaraco/skeleton/issues/1
